version: "3.8"

services:
  database:
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wfws
      MYSQL_USER: wfws
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  webshop:
    depends_on:
      - database
      - rabbitMQ
      - mongoDB
    container_name: wfws
    build:
      context: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_URL: database:3306/wfws
      DB_USER: wfws
      DB_PASS: password
  rabbitMQ:
    image: 'rabbitmq:latest'
    restart: unless-stopped
    environment:
      host: localhost
      username: guest
      password: guest
    ports:
      - "5672:5672"
  mongoDB:
    image: mongo:latest
    restart: unless-stopped
    hostname: localhost
    ports:
      - "27017:27017"
volumes:
  db:

