spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo #${DB_URL}
    username: developer #${DB_USER}
    password: password #${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoDB

